window.RELEASES_TODAY = "2025-11-15";
window.RELEASED_TRACKS_DATA = [
  { slug: "chernyy-yashchik", title: "Черный ящик", releaseDate: "скоро", access: "early-access" },
  { slug: "zima", title: "Зима", releaseDate: "скоро", access: "early-access" },
  { slug: "pomni", title: "Помни", releaseDate: "скоро", access: "early-access" },
  { slug: "okean-vnutri", title: "Океан внутри", releaseDate: "скоро", access: "early-access" },
  { slug: "o-vsevyshniy", title: "О Всевышний", releaseDate: "скоро", access: "early-access" },
  { slug: "kak-yad", title: "Как яд", releaseDate: "скоро", access: "early-access" },
  { slug: "allakh", title: "Аллах", releaseDate: "скоро", access: "early-access" },
  { slug: "peregrev", title: "Перегрев", releaseDate: "27.11.2025", access: "early-access" },
  { slug: "leti-so-mnoy", title: "Лети со мной", releaseDate: "29.11.2025", access: "early-access" },
  { slug: "sirena", title: "Сирена", releaseDate: "25.11.2025", access: "early-access" },
  { slug: "ierarkhiya", title: "Иерархия", releaseDate: "скоро", access: "early-access" },
  { slug: "ona-sryvala-rozy-20", title: "Она срывала розы 2.0", releaseDate: "скоро", access: "early-access" },
  { slug: "ona-sryvala-rozy", title: "Она срывала розы", releaseDate: "22.07.2025" },
  { slug: "nemnozhko", title: "Немножко", releaseDate: "28.11.2025", audioExt: ".wav", access: "early-access" },
  { slug: "pachka-sigaret", title: "Пачка сигарет", releaseDate: "скоро", access: "early-access" },
  { slug: "yashlek", title: "Яшьлек", releaseDate: "28.11.2025", access: "early-access" },
  { slug: "eto-vetru-govoril", title: "Это ветру говорил", releaseDate: "29.11.2025", access: "early-access" },
  { slug: "mir-naiznanku", title: "Мир наизнанку", releaseDate: "скоро", access: "early-access" },
  { slug: "karusel", title: "Карусель", releaseDate: "скоро", access: "early-access" },
  { slug: "dikaya-kometa", title: "Дикая комета", releaseDate: "28.11.2025", access: "early-access" },
  { slug: "mamaamakriminal", title: "МамаамаКриминал", releaseDate: "скоро", access: "early-access" },
  { slug: "ekho-shagov", title: "Эхо шагов", releaseDate: "скоро", access: "early-access" },
  { slug: "ayforio", title: "Айфорио", releaseDate: "30.11.2025", access: "early-access" },
  { slug: "bez-imeni", title: "Без имени", releaseDate: "01.12.2025", access: "early-access" },
  { slug: "spichki", title: "Спички", releaseDate: "12.08.2025" },
  { slug: "poka-dyshu", title: "Пока дышу", releaseDate: "27.07.2025", type: "EP" },
  { slug: "puls", title: "Пульс", releaseDate: "27.07.2025", type: "EP" },
  { slug: "ne-veryu", title: "Не верю", releaseDate: "27.07.2025", type: "EP" },
  { slug: "uliver", title: "Уливер", releaseDate: "27.07.2025", type: "EP" },
  { slug: "sotri-menya", title: "Сотри меня", releaseDate: "27.07.2025", type: "EP" }
];
