window.RELEASES_TODAY = "2025-11-15";
window.RELEASED_TRACKS_DATA = [
  { slug: "davyl", title: "Давыл", releaseDate: "Скоро", access: "early-access", price: 1, languages: ["ru", "tt"], copyright: "© 2025 AVZALØV. All rights reserved.", plays: Math.floor(Math.random() * 1000) },
  { slug: "the-psychopath", title: "Психопат", releaseDate: "Скоро", access: "early-access", price: 1, languages: ["ru", "tt"], copyright: "© 2025 AVZALØV. All rights reserved.", plays: Math.floor(Math.random() * 1000) },
  { slug: "teapot", title: "Чайник", releaseDate: "Скоро", access: "early-access", price: 1, languages: ["ru", "tt"], copyright: "© 2025 AVZALØV. All rights reserved.", plays: Math.floor(Math.random() * 1000) },
  {
    slug: "davyl",
    title: "Давыл",
    releaseDate: "Скоро",
    price: 0,
    cover: "Davyl",
    audio: "Davyl",
    copyright: "© 2025 AVZALØV. Все права защищены.",
    plays: Math.floor(Math.random() * 1000)
  },
  {
    slug: "the-psychopath",
    title: "Психопат",
    releaseDate: "Скоро",
    price: 0,
    cover: "The psychopath",
    audio: "The psychopath",
    copyright: "© 2025 AVZALØV. Все права защищены.",
    plays: Math.floor(Math.random() * 1000)
  },
  {
    slug: "teapot",
    title: "Чайник",
    releaseDate: "Скоро",
    price: 0,
    cover: "Teapot",
    audio: "Teapot",
    copyright: "© 2025 AVZALØV. Все права защищены.",
    plays: Math.floor(Math.random() * 1000)
  },
  { slug: "chernyy-yashchik", title: "Черный ящик", releaseDate: "скоро", access: "early-access", price: 1, copyright: "© 2025 AVZALØV. Все права защищены.", plays: Math.floor(Math.random() * 1000) },
  { slug: "zima", title: "Зима", releaseDate: "скоро", access: "early-access", price: 1, copyright: "© 2025 AVZALØV. Все права защищены.", plays: Math.floor(Math.random() * 1000) },
  { slug: "pomni", title: "Помни", releaseDate: "скоро", access: "early-access", price: 1, copyright: "© 2025 AVZALØV. Все права защищены.", plays: Math.floor(Math.random() * 1000) },
  { slug: "okean-vnutri", title: "Океан внутри", releaseDate: "скоро", access: "early-access", price: 1, copyright: "© 2025 AVZALØV. Все права защищены.", coverExt: ".png", plays: Math.floor(Math.random() * 1000) },
  { slug: "o-vsevyshniy", title: "О Всевышний", releaseDate: "скоро", access: "early-access", price: 1, copyright: "© 2025 AVZALØV. Все права защищены.", plays: Math.floor(Math.random() * 1000) },
  { slug: "kak-yad", title: "Как яд", releaseDate: "скоро", access: "early-access", price: 1, copyright: "© 2025 AVZALØV. Все права защищены.", plays: Math.floor(Math.random() * 1000) },
  { slug: "allakh", title: "Аллах", releaseDate: "скоро", access: "early-access", price: 1, copyright: "© 2025 AVZALØV. Все права защищены.", plays: Math.floor(Math.random() * 1000) },
  { slug: "peregrev", title: "Перегрев", releaseDate: "27.11.2025", access: "early-access", price: 1, copyright: "© 2025 AVZALØV. Все права защищены.", plays: Math.floor(Math.random() * 1000) },
  { slug: "leti-so-mnoy", title: "Лети со мной", releaseDate: "29.11.2025", access: "early-access", price: 1, copyright: "© 2025 AVZALØV. Все права защищены.", plays: Math.floor(Math.random() * 1000) },
  { slug: "sirena", title: "Сирена", releaseDate: "25.11.2025", access: "early-access", price: 1, copyright: "© 2025 AVZALØV. Все права защищены.", plays: Math.floor(Math.random() * 1000) },
  { slug: "ierarkhiya", title: "Иерархия", releaseDate: "скоро", access: "early-access", price: 1, copyright: "© 2025 AVZALØV. Все права защищены.", plays: Math.floor(Math.random() * 1000) },
  { slug: "ona-sryvala-rozy-20", title: "Она срывала розы 2.0", releaseDate: "скоро", access: "early-access", price: 1, copyright: "© 2025 AVZALØV. Все права защищены.", plays: Math.floor(Math.random() * 1000) },
  { slug: "ona-sryvala-rozy", title: "Она срывала розы", releaseDate: "22.07.2025", price: 0, hasClip: true, clipUrl: "https://youtu.be/avzalov-rosy", copyright: "© 2025 AVZALØV. Все права защищены.", plays: Math.floor(Math.random() * 1000) },
  { slug: "nemnozhko", title: "Немножко", releaseDate: "28.11.2025", audioExt: ".wav", access: "early-access", price: 1, hasClip: true, clipUrl: "https://youtu.be/avzalov-nemnozhko", copyright: "© 2025 AVZALØV. Все права защищены.", coverExt: ".jpg", plays: Math.floor(Math.random() * 1000) },
  { slug: "pachka-sigaret", title: "Пачка сигарет", releaseDate: "скоро", access: "early-access", price: 1, copyright: "© 2025 AVZALØV. Все права защищены.", plays: Math.floor(Math.random() * 1000) },
  { slug: "yashlek", title: "Яшьлек", releaseDate: "28.11.2025", access: "early-access", price: 1, hasClip: true, clipUrl: "https://youtu.be/avzalov-yashlek", copyright: "© 2025 AVZALØV. Все права защищены.", plays: Math.floor(Math.random() * 1000) },
  { slug: "eto-vetru-govoril", title: "Это ветру говорил", releaseDate: "29.11.2025", access: "early-access", price: 1, copyright: "© 2025 AVZALØV. Все права защищены.", coverExt: ".png", plays: Math.floor(Math.random() * 1000) },
  { slug: "mir-naiznanku", title: "Мир наизнанку", releaseDate: "скоро", access: "early-access", price: 1, audio: false, copyright: "© 2025 AVZALØV. Все права защищены.", plays: Math.floor(Math.random() * 1000) },
  { slug: "karusel", title: "Карусель", releaseDate: "скоро", access: "early-access", price: 1, copyright: "© 2025 AVZALØV. Все права защищены.", plays: Math.floor(Math.random() * 1000) },
  { slug: "dikaya-kometa", title: "Дикая комета", releaseDate: "28.11.2025", access: "early-access", price: 1, hasClip: true, clipUrl: "https://youtu.be/avzalov-kometa", copyright: "© 2025 AVZALØV. Все права защищены.", plays: Math.floor(Math.random() * 1000) },
  { slug: "mamaamakriminal", title: "МамаамаКриминал", releaseDate: "скоро", access: "early-access", price: 1, copyright: "© 2025 AVZALØV. Все права защищены.", plays: Math.floor(Math.random() * 1000) },
  { slug: "molchaniyami", title: "Молчаниями", releaseDate: "30.11.2025", access: "early-access", price: 1, coverExt: ".jpg", copyright: "© 2025 AVZALØV. Все права защищены.", plays: Math.floor(Math.random() * 1000) },
  { slug: "ekho-shagov", title: "Эхо шагов", releaseDate: "скоро", access: "early-access", price: 1, copyright: "© 2025 AVZALØV. Все права защищены.", plays: Math.floor(Math.random() * 1000) },
  { slug: "ayforio", title: "Айфорио", releaseDate: "30.11.2025", access: "early-access", price: 1, copyright: "© 2025 AVZALØV. Все права защищены.", plays: Math.floor(Math.random() * 1000) },
  { slug: "bez-imeni", title: "Без имени", releaseDate: "01.12.2025", access: "early-access", price: 1, copyright: "© 2025 AVZALØV. Все права защищены.", plays: Math.floor(Math.random() * 1000) },
  { slug: "spichki", title: "Спички", releaseDate: "12.08.2025", price: 0, hasClip: true, clipUrl: "https://youtu.be/avzalov-spichki", copyright: "© 2025 AVZALØV. Все права защищены.", plays: Math.floor(Math.random() * 1000) },
  { slug: "poka-dyshu", title: "Пока дышу", releaseDate: "27.07.2025", type: "EP", price: 0, copyright: "© 2025 AVZALØV. Все права защищены.", plays: Math.floor(Math.random() * 1000) },
  { slug: "puls", title: "Пульс", releaseDate: "27.07.2025", type: "EP", price: 0, copyright: "© 2025 AVZALØV. Все права защищены.", plays: Math.floor(Math.random() * 1000) },
  { slug: "ne-veryu", title: "Не верю", releaseDate: "27.07.2025", type: "EP", price: 0, copyright: "© 2025 AVZALØV. Все права защищены.", plays: Math.floor(Math.random() * 1000) },
  { slug: "uliver", title: "Уливер", releaseDate: "27.07.2025", type: "EP", price: 0, copyright: "© 2025 AVZALØV. Все права защищены.", plays: Math.floor(Math.random() * 1000) },
  { slug: "sotri-menya", title: "Сотри меня", releaseDate: "27.07.2025", type: "EP", price: 0, copyright: "© 2025 AVZALØV. Все права защищены.", plays: Math.floor(Math.random() * 1000) }
];


